apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tufinca-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: tufinca-ingress  # Replace with your actual domain
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: tufinca-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tufinca-frontend-service  # Your frontend service name
            port:
              number: 80
